version: '3.4'

services:
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: qualyteamrootpw
      MYSQL_DATABASE: qualyteamdb
      MYSQL_USER: qualyteam
      MYSQL_PASSWORD: qualyteampw
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
