// <auto-generated />
using System;
using DesafioQualyTeam.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DesafioQualyTeam.API.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("DesafioQualyTeam.API.Entities.Arquivo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("Criacao")
                        .HasColumnType("datetime(6)");

                    b.Property<byte[]>("Dados")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<Guid>("DetalhesArquivoId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UltimaAtualizacao")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("DetalhesArquivoId")
                        .IsUnique();

                    b.ToTable("Arquivos");
                });

            modelBuilder.Entity("DesafioQualyTeam.API.Entities.DetalhesArquivo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Criacao")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("DocumentoId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UltimaAtualizacao")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("DocumentoId")
                        .IsUnique();

                    b.ToTable("DetalhesArquivos");
                });

            modelBuilder.Entity("DesafioQualyTeam.API.Entities.Documento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("Criacao")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("ProcessoId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UltimaAtualizacao")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("ProcessoId");

                    b.ToTable("Documentos");
                });

            modelBuilder.Entity("DesafioQualyTeam.API.Entities.Processo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("Criacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UltimaAtualizacao")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Processos");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8a0e1284-8b83-4d75-a5b8-7427ac40f7c0"),
                            Criacao = new DateTime(2022, 11, 19, 15, 22, 40, 715, DateTimeKind.Local).AddTicks(751),
                            Nome = "Processo_01",
                            UltimaAtualizacao = new DateTime(2022, 11, 19, 15, 22, 40, 715, DateTimeKind.Local).AddTicks(751)
                        },
                        new
                        {
                            Id = new Guid("600f3fda-d690-4116-b7ab-1c7740fd46c3"),
                            Criacao = new DateTime(2022, 11, 19, 15, 22, 40, 715, DateTimeKind.Local).AddTicks(787),
                            Nome = "Processo_02",
                            UltimaAtualizacao = new DateTime(2022, 11, 19, 15, 22, 40, 715, DateTimeKind.Local).AddTicks(787)
                        },
                        new
                        {
                            Id = new Guid("ee5fe867-fe4e-40d3-bda6-9ee6d3d71714"),
                            Criacao = new DateTime(2022, 11, 19, 15, 22, 40, 715, DateTimeKind.Local).AddTicks(794),
                            Nome = "Processo_03",
                            UltimaAtualizacao = new DateTime(2022, 11, 19, 15, 22, 40, 715, DateTimeKind.Local).AddTicks(794)
                        },
                        new
                        {
                            Id = new Guid("b4185d9e-f665-4bee-b764-ade04036354e"),
                            Criacao = new DateTime(2022, 11, 19, 15, 22, 40, 715, DateTimeKind.Local).AddTicks(800),
                            Nome = "Processo_04",
                            UltimaAtualizacao = new DateTime(2022, 11, 19, 15, 22, 40, 715, DateTimeKind.Local).AddTicks(800)
                        },
                        new
                        {
                            Id = new Guid("66f30ab7-fc63-4347-9c94-755d8c0f790f"),
                            Criacao = new DateTime(2022, 11, 19, 15, 22, 40, 715, DateTimeKind.Local).AddTicks(804),
                            Nome = "Processo_05",
                            UltimaAtualizacao = new DateTime(2022, 11, 19, 15, 22, 40, 715, DateTimeKind.Local).AddTicks(804)
                        });
                });

            modelBuilder.Entity("DesafioQualyTeam.API.Entities.Arquivo", b =>
                {
                    b.HasOne("DesafioQualyTeam.API.Entities.DetalhesArquivo", null)
                        .WithOne("Arquivo")
                        .HasForeignKey("DesafioQualyTeam.API.Entities.Arquivo", "DetalhesArquivoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DesafioQualyTeam.API.Entities.DetalhesArquivo", b =>
                {
                    b.HasOne("DesafioQualyTeam.API.Entities.Documento", null)
                        .WithOne("DetalheArquivo")
                        .HasForeignKey("DesafioQualyTeam.API.Entities.DetalhesArquivo", "DocumentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DesafioQualyTeam.API.Entities.Documento", b =>
                {
                    b.HasOne("DesafioQualyTeam.API.Entities.Processo", "Processo")
                        .WithMany()
                        .HasForeignKey("ProcessoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Processo");
                });

            modelBuilder.Entity("DesafioQualyTeam.API.Entities.DetalhesArquivo", b =>
                {
                    b.Navigation("Arquivo");
                });

            modelBuilder.Entity("DesafioQualyTeam.API.Entities.Documento", b =>
                {
                    b.Navigation("DetalheArquivo");
                });
#pragma warning restore 612, 618
        }
    }
}
